/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;


public class App {
    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        // AutomateSearchAmazon searchAmazonObj = new AutomateSearchAmazon();
        // searchAmazonObj.searchAmazon();

        // BookMyShowHyperLink countLink  = new BookMyShowHyperLink();
        // countLink.hyperLinkCount();

        // LinkedinPost post = new LinkedinPost();
        // post.automatePost();
       
        ImageUrl imgSrc = new ImageUrl();
        imgSrc.getImageSrc();
        
    }
}
